import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider = ({ children }: LanguageProviderProps) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    const keys = key.split('.');
    let value: any = translations[language];
    
    for (const k of keys) {
      value = value?.[k];
    }
    
    return value || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

const translations = {
  en: {
    nav: {
      home: 'Home',
      modules: 'Modules',
      about: 'About',
      contact: 'Contact',
      imprint: 'Imprint',
      guidedSimulator: 'Guided Simulator',
      promptPlayground: 'Prompt Playground'
    },
    landing: {
      hero: {
        title: 'PromptED: Responsible AI use in Journalism',
        subtitle: 'A hands-on exploration and practice for journalists to observe how large language models function, their limitations, and how to use them for more trustworthy content production.',
        watchTrailer: 'Watch Trailer'
      },
      features: {
        simulator: {
          title: 'Guided Simulator',
          description: 'Interactive guide: explore how LLMs work and how to responsibly interact with them'
        },
        playground: {
          title: 'Prompt Playground',
          description: 'Apply your knowledge: experiment with your own prompts'
        },
        debunker: {
          title: 'AI Claim Debunker',
          description: 'Put your skills to work: review claims and gain counter perspectives'
        }
      },
      footer: {
        llmUsage: 'LLMs have been used in the following ways:',
        guidedExploration: 'Guided Exploration:',
        guidedExplorationDesc: 'To create prompt-output examples.',
        promptPlayground: 'Prompt Playground:',
        promptPlaygroundDesc: 'To optimize prompts, generate outputs and to identify factual inaccuracies and bias.',
        modelsUsed: 'Models used:',
        models: 'Llama 3.1 8B, Mistral, Claude, ChatGPT',
        euFunding: "Funded by the European Union's Horizon Europe Programme (Grant 101135437)"
      }
    },
    modules: {
      title: 'Modules',
      comingSoon: 'Coming soon...',
      introduction: 'Introduction',
      nextWordPrediction: 'Next Word Prediction',
      promptConstruction: 'Prompt Construction'
    },
    intro: {
      aboutSimulator: {
        label: 'About this Simulator',
        title: 'What is a "Guided Simulator"?',
        description: 'A structured walkthrough of case studies generated by real-life LLM outputs that demonstrate key learnings. Interact at set points—sometimes more, sometimes less—always with clear guidance.',
        llmsUsed: 'LLMs used in the generation of text include: Mistral, Claude, Chat GPT & Llama 3.1 8B',
        continue: 'Continue'
      },
      base: {
        label: 'Introduction',
        title: 'Reporting on the EU AI Act',
        description: "In this simulator, you'll step into the role of a journalist preparing an article on the EU AI Act. Rather than starting from scratch, you'll work with preset prompts and see the real outputs generated by a large language model.",
        startSimulator: 'Start Simulator'
      }
    },
    nextWord: {
      intro: {
        label: 'Learning 1: Next word prediction',
        title: 'How do LLMs form responses to user prompts?',
        description: 'LLMs generate text by predicting what word should come next. For each prediction, previous words are analysed to calculate probabilities for all possible next words. The most probable word is selected, added to the text, and then used in this updated context to predict the next word, continuing until complete.',
        continue: 'Continue'
      },
      prompt: {
        input: 'Write a headline for a long form journalistic article about ai ethics agreement reached across the eu',
        popoverSubmit: "Click here to submit your prompt and see the AI's response!"
      },
      response: {
        miniTaskTitle: 'Mini Task: Find the factual inaccuracy',
        miniTaskDescription: 'Click on the green highlighted words to try out different combinations – each combination will generate a different outcome.',
        interactiveTitle: 'Interactive Word Selection',
        interactiveDesc: 'Click on the highlighted words to select a different option. Try and find the word combination that leads to a factual inaccuracy.',
        probTooltip: 'These are example probabilities that could be assigned to a word that weights words to be selected by the LLM.'
      },
      takeaways: {
        title: 'Takeaways:',
        subtitle: 'How do LLMs form responses to user prompts?',
        point1Title: 'LLMs generate text through next-word prediction',
        point1: '—a probabilistic process that relies on patterns in data rather than logical reasoning.',
        point2Title: 'Because of this stochastic nature, errors are inevitable:',
        point2: ' advanced models will produce mistakes, distortions, or unfounded claims.',
        point3Title: 'As a journalist, your critical expertise is essential:',
        point3: ' apply your analytical skills to evaluate AI outputs, filter out misinformation, and prevent LLM falsehoods from entering your reporting.',
        nextTask: 'Next Task →'
      }
    },
    promptConstructionModule: {
      intro: {
        label: 'Learning 2: Prompt construction',
        title: "How does my input affect the quality of the LLM's output?",
        description: "Your prompt directly shapes an LLM's response. Large language models use the wording, specificity, and context in your wording to help decide how to reply, meaning the quality of the output can depend heavily on how you phrase it. Explore how real LLM generated responses change with different prompt constructions",
        continue: 'Continue'
      },
      specificity: {
        input: 'Summarize the main points of the EU AI Act, including its risk categories and rules for high-risk AI systems.',
        popoverSubmit: "Click here to submit your prompt and see the AI's response!"
      },
      summarize: {
        addDocument: 'Add document',
        documentAttached: 'Document attached',
        fileName: 'EU_AI_Act.pdf'
      },
      takeaways: {
        title: 'Takeaways:',
        subtitle: "How does my input affect the quality of the LLM's output?",
        point1Title: 'How you prompt directly impacts LLM output:',
        point1: ' An LLM will use your word choice and information provided to try and form an appropriate response.',
        point2Title: "You don't need to interact conversationally:",
        point2: " Interacting in a human-like manner may only increase the plausibility of the LLM's response and make it harder to evaluate.",
        point3Title: 'Look out for key parameters to get better results:',
        point3: ' Include context, specificity and phrase your prompts in a neutral, technical manner',
        promptPlayground: 'Prompt Playground'
      }
    },
    about: {
      title: 'About',
      description: 'This is the About page. Information about the project will be added here soon.'
    },
    contact: {
      title: 'Contact',
      description: 'Contact information will be added here soon.'
    },
    imprint: {
      title: 'Imprint',
      description: 'This is the Imprint page. Legal information and impressum will be added here soon.'
    },
    systemParameters: {
      title: 'System Parameters',
      comingSoon: 'Coming soon...'
    },
    llmTraining: {
      title: 'LLM Training',
      comingSoon: 'Coming soon...'
    },
    multipleSources: {
      title: 'Multiple Sources',
      comingSoon: 'Coming soon...'
    },
    journalisticEvaluation: {
      title: 'Journalistic Evaluation',
      comingSoon: 'Coming soon...'
    },
    promptConstruction: {
      title: 'Prompt Construction',
      bias: {
        title: 'Bias',
        comingSoon: 'Coming soon...'
      },
      context: {
        title: 'Context',
        comingSoon: 'Coming soon...'
      },
      conversationStyle: {
        title: 'Conversation Style',
        comingSoon: 'Coming soon...'
      }
    },
    components: {
      miniTask: {
        startTask: 'Start Task'
      },
      breadcrumb: {
        home: 'Home',
        guidedSimulation: 'Guided Simulation',
        modules: 'Modules',
        takeaways: 'Takeaways'
      },
      moduleNavigation: {
        previous: 'Previous',
        next: 'Next'
      },
      learningProgressBar: {
        intro: 'Introduction',
        guidedExploration: 'Guided Exploration',
        takeaways: 'Takeaways'
      },
      evaluationPanel: {
        title: 'Journalistic Evaluation',
        minimize: 'Minimize evaluation panel',
        expand: 'Open evaluation panel',
        cannotMinimize: 'Panel cannot be minimized right now',
        criteria: {
          factualAccuracy: {
            label: 'Factual Accuracy',
            description: 'Factual accuracy in an LLM output ensures that information provided is correct and aligns with real-world knowledge, which is crucial for reliable, trustworthy results. A part of this are hallucinations, when the AI generates information that appears plausible but is factually incorrect or entirely fabricated; often because it extrapolates from incorrect training data, lacks real-world context, or misunderstands the user\'s query.'
          },
          relevance: {
            label: 'Relevance',
            description: 'Relevance measures how well the response matches the topic or intent of the prompt. If the prompt is not specific enough, the LLM output may leave out key information that affects a journalist\'s pool of information to draw from.'
          },
          voice: {
            label: 'Voice',
            description: 'Voice refers to the tone, style, or \'personality\' conveyed in the response, which can be shaped by specifying so in the prompt. When the voice of a prompt is human-like, LLM outputs are made to seem more plausible and knowledgeable, effectively disguising other aspects discussed.'
          },
          bias: {
            label: 'Bias',
            description: 'Bias refers to prejudices and unbalanced narratives outputted by LLMs due to biased training data, model architecture or prompt instructions. LLMs will always have a degree of bias in its representation of different topics and therefore can bias the journalist\'s piece of work.'
          },
          plagiarism: {
            label: 'Plagiarism',
            description: 'LLMs can plagiarise by directly taking content from training data. While some LLMs are able to attribute pieces of information, all LLMs have the ability to lose connection to data sources, making them vulnerable to reproducing substantial portions of text from data. User should be wary of this, even when the output has sources cited.'
          }
        }
      },
      promptControls: {
        title: 'Prompt Controls',
        original: 'Original',
        specificity: {
          title: 'Specificity',
          left: 'More General',
          right: 'More Specific',
          info: 'Control how detailed your prompt is. General prompts allow more AI interpretation, while specific prompts provide precise instructions.'
        },
        conversationStyle: {
          title: 'Conversation Style',
          left: 'More Conversational',
          right: 'More Instructional',
          info: 'Choose between a conversational tone (informal, friendly) or instructional tone (direct, command-like).'
        },
        context: {
          title: 'Context Provided',
          left: 'Less Background',
          right: 'More Background',
          info: 'Decide whether to provide background information about your role or situation in the prompt.'
        },
        bias: {
          title: 'Confirmation Bias',
          left: 'Less Bias',
          right: 'More Bias',
          info: 'Explore how neutral or leading prompts can effect and bias LLM output'
        },
        sendOptimizedPrompt: 'Send Optimized Prompt',
        sendPrompt: 'Send Prompt',
        promptSpecificity: 'Prompt Specificity',
        interactionStyle: 'Interaction Style',
        promptSpecificityInfo: 'Prompt Specificity is how explicit you are in your prompt for the desired output. The more specific you are, the better the results will be.',
        interactionStyleInfo: 'Conversation Style is the manner in which you prompt your LLM. You can interact like it is human but this is not necessary.',
        contextInfo: 'Context is the additional information you give to the LLM to help it answers as well as possible. This may include background to your prompt',
        biasInfo: 'Confirmation bias is when the way you phrase a prompt affects the perspective the LLM produces'
      }
    }
  },
  es: {
    nav: {
      home: 'Inicio',
      modules: 'Módulos',
      about: 'Acerca de',
      contact: 'Contacto',
      imprint: 'Aviso Legal',
      guidedSimulator: 'Simulador Guiado',
      promptPlayground: 'Campo de Práctica de Prompts'
    },
    landing: {
      hero: {
        title: 'PromptED: Uso Responsable de IA en Periodismo',
        subtitle: 'Una exploración y práctica para periodistas para observar cómo funcionan los modelos de lenguaje grandes, sus limitaciones y cómo usarlos para una producción de contenido más confiable.',
        watchTrailer: 'Ver Tráiler'
      },
      features: {
        simulator: {
          title: 'Simulador Guiado',
          description: 'Guía interactiva: explora cómo funcionan los LLM y cómo interactuar responsablemente con ellos'
        },
        playground: {
          title: 'Campo de Práctica de Prompts',
          description: 'Aplica tus conocimientos: experimenta con tus propios prompts'
        },
        debunker: {
          title: 'Verificador de Afirmaciones de IA',
          description: 'Pon tus habilidades a trabajar: revisa afirmaciones y obtén perspectivas contrarias'
        }
      },
      footer: {
        llmUsage: 'Los LLM se han utilizado de las siguientes maneras:',
        guidedExploration: 'Exploración Guiada:',
        guidedExplorationDesc: 'Para crear ejemplos de prompt-salida.',
        promptPlayground: 'Campo de Práctica de Prompts:',
        promptPlaygroundDesc: 'Para optimizar prompts, generar salidas e identificar inexactitudes factuales y sesgos.',
        modelsUsed: 'Modelos utilizados:',
        models: 'Llama 3.1 8B, Mistral, Claude, ChatGPT',
        euFunding: "Financiado por el Programa Horizonte Europa de la Unión Europea (Subvención 101135437)"
      }
    },
    modules: {
      title: 'Módulos',
      comingSoon: 'Próximamente...',
      introduction: 'Introducción',
      nextWordPrediction: 'Predicción de Siguiente Palabra',
      promptConstruction: 'Construcción de Prompts'
    },
    intro: {
      aboutSimulator: {
        label: 'Acerca de este Simulador',
        title: '¿Qué es un "Simulador Guiado"?',
        description: 'Un recorrido estructurado de estudios de caso generados por salidas de LLM de la vida real que demuestran aprendizajes clave. Interactúa en puntos establecidos, a veces más, a veces menos, siempre con una guía clara.',
        llmsUsed: 'LLMs utilizados en la generación de texto incluyen: Mistral, Claude, Chat GPT y Llama 3.1 8B',
        continue: 'Continuar'
      },
      base: {
        label: 'Introducción',
        title: 'Reportaje sobre la Ley de IA de la UE',
        description: 'En este simulador, asumirás el papel de un periodista preparando un artículo sobre la Ley de IA de la UE. En lugar de comenzar desde cero, trabajarás con prompts predefinidos y verás las salidas reales generadas por un modelo de lenguaje grande.',
        startSimulator: 'Iniciar Simulador'
      }
    },
    nextWord: {
      intro: {
        label: 'Aprendizaje 1: Predicción de siguiente palabra',
        title: '¿Cómo forman los LLM respuestas a las indicaciones del usuario?',
        description: 'Los LLM generan texto prediciendo qué palabra debe venir a continuación. Para cada predicción, se analizan las palabras anteriores para calcular probabilidades para todas las palabras siguientes posibles. Se selecciona la palabra más probable, se añade al texto y luego se usa en este contexto actualizado para predecir la siguiente palabra, continuando hasta completarse.',
        continue: 'Continuar'
      },
      prompt: {
        input: "Escribe un titular para un artículo periodístico de formato largo sobre el acuerdo de ética de IA alcanzado en toda la UE",
        popoverSubmit: "Haz clic aquí para enviar tu prompt y ver la respuesta de la IA"
      },
      response: {
        miniTaskTitle: 'Mini Tarea: Encuentra la inexactitud factual',
        miniTaskDescription: 'Haz clic en las palabras resaltadas en verde para probar diferentes combinaciones; cada combinación generará un resultado diferente.',
        interactiveTitle: 'Selección Interactiva de Palabras',
        interactiveDesc: 'Haz clic en las palabras resaltadas para seleccionar una opción diferente. Intenta encontrar la combinación de palabras que conduce a una inexactitud factual.',
        probTooltip: 'Estas son probabilidades de ejemplo que podrían asignarse a una palabra que pondera las palabras a ser seleccionadas por el LLM.'
      },
      takeaways: {
        title: 'Conclusiones:',
        subtitle: '¿Cómo forman los LLM respuestas a las indicaciones del usuario?',
        point1Title: 'Los LLM generan texto mediante predicción de siguiente palabra',
        point1: '—un proceso probabilístico que se basa en patrones en los datos en lugar de razonamiento lógico.',
        point2Title: 'Debido a esta naturaleza estocástica, los errores son inevitables:',
        point2: ' los modelos avanzados producirán errores, distorsiones o afirmaciones infundadas.',
        point3Title: 'Como periodista, tu experiencia crítica es esencial:',
        point3: ' aplica tus habilidades analíticas para evaluar las salidas de IA, filtrar la desinformación y evitar que las falsedades de LLM entren en tus reportajes.',
        nextTask: 'Siguiente Tarea →'
      }
    },
    promptConstructionModule: {
      intro: {
        label: 'Aprendizaje 2: Construcción de prompts',
        title: '¿Cómo afecta mi entrada a la calidad de la salida del LLM?',
        description: 'Tu prompt da forma directamente a la respuesta de un LLM. Los modelos de lenguaje grandes utilizan la redacción, especificidad y contexto en tu redacción para ayudar a decidir cómo responder, lo que significa que la calidad de la salida puede depender en gran medida de cómo lo formules. Explora cómo cambian las respuestas reales generadas por LLM con diferentes construcciones de prompts',
        continue: 'Continuar'
      },
      specificity: {
        input: 'Resume los puntos principales de la Ley de IA de la UE, incluyendo sus categorías de riesgo y reglas para sistemas de IA de alto riesgo.',
        popoverSubmit: "Haz clic aquí para enviar tu prompt y ver la respuesta de la IA"
      },
      summarize: {
        addDocument: 'Agregar documento',
        documentAttached: 'Documento adjunto',
        fileName: 'Ley_IA_UE.pdf'
      },
      takeaways: {
        title: 'Conclusiones:',
        subtitle: '¿Cómo afecta mi entrada a la calidad de la salida del LLM?',
        point1Title: 'Cómo haces tu prompt impacta directamente la salida del LLM:',
        point1: ' Un LLM utilizará tu elección de palabras e información proporcionada para intentar formar una respuesta apropiada.',
        point2Title: 'No necesitas interactuar conversacionalmente:',
        point2: ' Interactuar de manera similar a un humano solo puede aumentar la plausibilidad de la respuesta del LLM y hacerla más difícil de evaluar.',
        point3Title: 'Busca parámetros clave para obtener mejores resultados:',
        point3: ' Incluye contexto, especificidad y formula tus prompts de manera neutral y técnica',
        promptPlayground: 'Campo de Práctica de Prompts'
      }
    },
    about: {
      title: 'Acerca de',
      description: 'Esta es la página Acerca de. La información sobre el proyecto se agregará aquí pronto.'
    },
    contact: {
      title: 'Contacto',
      description: 'La información de contacto se agregará aquí pronto.'
    },
    imprint: {
      title: 'Aviso Legal',
      description: 'Esta es la página de Aviso Legal. La información legal se agregará aquí pronto.'
    },
    systemParameters: {
      title: 'Parámetros del Sistema',
      comingSoon: 'Próximamente...'
    },
    llmTraining: {
      title: 'Entrenamiento LLM',
      comingSoon: 'Próximamente...'
    },
    multipleSources: {
      title: 'Múltiples Fuentes',
      comingSoon: 'Próximamente...'
    },
    journalisticEvaluation: {
      title: 'Evaluación Periodística',
      comingSoon: 'Próximamente...'
    },
    promptConstruction: {
      title: 'Construcción de Prompts',
      bias: {
        title: 'Sesgo',
        comingSoon: 'Próximamente...'
      },
      context: {
        title: 'Contexto',
        comingSoon: 'Próximamente...'
      },
      conversationStyle: {
        title: 'Estilo de Conversación',
        comingSoon: 'Próximamente...'
      }
    },
    components: {
      miniTask: {
        startTask: 'Iniciar Tarea'
      },
      breadcrumb: {
        home: 'Inicio',
        guidedSimulation: 'Simulación Guiada',
        modules: 'Módulos',
        takeaways: 'Conclusiones'
      },
      moduleNavigation: {
        previous: 'Anterior',
        next: 'Siguiente'
      },
      learningProgressBar: {
        intro: 'Introducción',
        guidedExploration: 'Exploración Guiada',
        takeaways: 'Conclusiones'
      },
      evaluationPanel: {
        title: 'Evaluación Periodística',
        minimize: 'Minimizar panel de evaluación',
        expand: 'Abrir panel de evaluación',
        cannotMinimize: 'El panel no se puede minimizar en este momento',
        criteria: {
          factualAccuracy: {
            label: 'Precisión Factual',
            description: 'La precisión factual en la salida de un LLM garantiza que la información proporcionada sea correcta y se alinee con el conocimiento del mundo real, lo cual es crucial para obtener resultados confiables y dignos de confianza. Una parte de esto son las alucinaciones, cuando la IA genera información que parece plausible pero es factualmente incorrecta o completamente fabricada; a menudo porque extrapola a partir de datos de entrenamiento incorrectos, carece de contexto del mundo real o malinterpreta la consulta del usuario.'
          },
          relevance: {
            label: 'Relevancia',
            description: 'La relevancia mide qué tan bien la respuesta coincide con el tema o la intención del mensaje. Si el mensaje no es lo suficientemente específico, la salida del LLM puede omitir información clave que afecta el conjunto de información del que dispone el periodista.'
          },
          voice: {
            label: 'Voz',
            description: 'La voz se refiere al tono, estilo o \'personalidad\' transmitida en la respuesta, que puede moldearse especificándolo en el mensaje. Cuando la voz de un mensaje es similar a la humana, las salidas de LLM parecen más plausibles y conocedoras, disfrazando efectivamente otros aspectos discutidos.'
          },
          bias: {
            label: 'Sesgo',
            description: 'El sesgo se refiere a prejuicios y narrativas desequilibradas producidas por LLM debido a datos de entrenamiento sesgados, arquitectura del modelo o instrucciones del mensaje. Los LLM siempre tendrán cierto grado de sesgo en su representación de diferentes temas y, por lo tanto, pueden sesgar el trabajo del periodista.'
          },
          plagiarism: {
            label: 'Plagio',
            description: 'Los LLM pueden plagiar tomando directamente contenido de los datos de entrenamiento. Si bien algunos LLM pueden atribuir piezas de información, todos los LLM tienen la capacidad de perder la conexión con las fuentes de datos, lo que los hace vulnerables a reproducir porciones sustanciales de texto de los datos. El usuario debe tener cuidado con esto, incluso cuando la salida tiene fuentes citadas.'
          }
        }
      },
      promptControls: {
        title: 'Controles de Prompt',
        original: 'Original',
        specificity: {
          title: 'Especificidad',
          left: 'Más General',
          right: 'Más Específico',
          info: 'Controla qué tan detallado es tu prompt. Los prompts generales permiten más interpretación de la IA, mientras que los prompts específicos proporcionan instrucciones precisas.'
        },
        conversationStyle: {
          title: 'Estilo de Conversación',
          left: 'Más Conversacional',
          right: 'Más Instructivo',
          info: 'Elige entre un tono conversacional (informal, amigable) o un tono instructivo (directo, tipo comando).'
        },
        context: {
          title: 'Contexto Proporcionado',
          left: 'Menos Antecedentes',
          right: 'Más Antecedentes',
          info: 'Decide si proporcionar información de antecedentes sobre tu papel o situación en el prompt.'
        },
        bias: {
          title: 'Sesgo de Confirmación',
          left: 'Menos Sesgo',
          right: 'Más Sesgo',
          info: 'Explora cómo los prompts neutrales o dirigidos pueden afectar y sesgar la salida del LLM'
        },
        sendOptimizedPrompt: 'Enviar Prompt Optimizado',
        sendPrompt: 'Enviar Prompt',
        promptSpecificity: 'Especificidad del Prompt',
        interactionStyle: 'Estilo de Interacción',
        promptSpecificityInfo: 'La especificidad del prompt es qué tan explícito eres en tu prompt para la salida deseada. Cuanto más específico seas, mejores serán los resultados.',
        interactionStyleInfo: 'El estilo de conversación es la manera en que le das prompts a tu LLM. Puedes interactuar como si fuera humano, pero esto no es necesario.',
        contextInfo: 'El contexto es la información adicional que le das al LLM para ayudarlo a responder lo mejor posible. Esto puede incluir antecedentes de tu prompt',
        biasInfo: 'El sesgo de confirmación es cuando la forma en que formulas un prompt afecta la perspectiva que produce el LLM'
      }
    }
  }
};
