import { useNavigate } from "react-router-dom";
import Header from "@/components/Header";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";

const AboutSimulator = () => {
  const navigate = useNavigate();

  const handleStartSimulator = () => {
    navigate("/module/next-word-prediction");
  };

  return (
    <div className="min-h-screen bg-background">
      <Header />
      
      <main className="container mx-auto px-6 py-8">
        <div className="max-w-4xl mx-auto flex items-center justify-center min-h-[600px] relative">
          <Card 
            className="transition-all duration-200"
            style={{
              boxSizing: 'border-box',
              display: 'flex',
              flexDirection: 'column',
              justifyContent: 'space-between',
              alignItems: 'flex-start',
              padding: '40px 50px',
              isolation: 'isolate',
              position: 'absolute',
              width: '845px',
              height: '450px',
              left: 'calc(50% - 845px/2 + 0.5px)',
              top: '80px',
              background: '#FFFFFF',
              border: '1px solid #C5C5C5',
              boxShadow: '0px 6px 15px rgba(62, 62, 62, 0.15)',
              borderRadius: '20px'
            }}
          >
            <CardContent className="p-0 w-full h-full flex flex-col justify-between">
              {/* About label */}
              <div>
                <span className="text-gray-500 text-sm">About this Simulator</span>
              </div>


              {/* Content section */}
              <div className="flex-1 flex flex-col justify-center">
                {/* Main heading */}
                <h1 className="text-3xl font-bold text-gray-900 leading-tight mb-4">
                  What is a "Guided Simulator"?
                </h1>

                {/* Description */}
                <p className="text-gray-600 text-lg leading-relaxed mb-6">
                  A structured walkthrough of case studies generated by real-life LLM outputs that demonstrate key learnings. Interact at set points—sometimes more, sometimes less—always with clear guidance.
                </p>

                {/* LLMs info */}
                <p className="text-gray-600 text-base leading-relaxed">
                  LLMs used in the generation of text include: Mistral, Claude, Chat GPT & Llama 3.1 8B
                </p>
              </div>

              {/* Button section */}
              <div>
                <Button 
                  onClick={handleStartSimulator}
                  className="transition-all duration-200"
                  style={{ 
                    display: 'flex',
                    flexDirection: 'row',
                    justifyContent: 'center',
                    alignItems: 'center',
                    padding: '15px 40px',
                    gap: '12px',
                    width: '220px',
                    height: '58px',
                    background: '#64DB96',
                    borderRadius: '100px',
                    border: 'none',
                    color: '#1F1F1F',
                    fontFamily: 'Manrope',
                    fontStyle: 'normal',
                    fontWeight: '700',
                    fontSize: '18px',
                    lineHeight: '28px'
                  }}
                >
                  Start Simulator
                  <svg width="10" height="8" viewBox="0 0 12 10" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M1 5H11M11 5L7 1M11 5L7 9" stroke="#1F1F1F" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
                  </svg>
                </Button>
              </div>
            </CardContent>
          </Card>
        </div>
      </main>
    </div>
  );
};

export default AboutSimulator;