import { useNavigate } from "react-router-dom";
import Header from "@/components/Header";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";

const AboutSimulator = () => {
  const navigate = useNavigate();

  const handleStartSimulator = () => {
    navigate("/module/next-word-prediction");
  };

  return (
    <div className="min-h-screen bg-background">
      <Header />
      
      <main className="container mx-auto px-6 py-8">
        <div className="max-w-4xl mx-auto flex items-center justify-center min-h-[600px] relative">
          <Card 
            className="transition-all duration-200"
            style={{
              boxSizing: 'border-box',
              display: 'flex',
              flexDirection: 'column',
              alignItems: 'flex-start',
              padding: '40px 50px 50px',
              gap: '30px',
              isolation: 'isolate',
              position: 'absolute',
              width: '845px',
              height: '450px',
              left: 'calc(50% - 845px/2 + 0.5px)',
              top: '80px',
              background: '#FFFFFF',
              border: '1px solid #C5C5C5',
              boxShadow: '0px 6px 15px rgba(62, 62, 62, 0.15)',
              borderRadius: '20px'
            }}
          >
            <CardContent className="p-0 w-full">
              {/* About label */}
              <div className="mb-6">
                <span className="text-gray-500 text-sm">About this Simulator</span>
              </div>

              {/* Traffic cone icon */}
              <div className="mb-6">
                <div className="w-16 h-16 relative">
                  <svg width="64" height="64" viewBox="0 0 64 64" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M32 8L24 48H40L32 8Z" fill="#64DB96"/>
                    <path d="M32 8L28 28H36L32 8Z" fill="#4ECCA3"/>
                    <path d="M20 52H44C46 54 46 56 44 56H20C18 56 18 54 20 52Z" fill="#8B8B8B"/>
                    <circle cx="32" cy="18" r="2" fill="#FFFFFF"/>
                    <circle cx="32" cy="28" r="2" fill="#FFFFFF"/>
                    <circle cx="32" cy="38" r="2" fill="#FFFFFF"/>
                  </svg>
                </div>
              </div>

              {/* Main heading */}
              <h1 className="text-3xl font-bold text-gray-900 leading-tight mb-4">
                What is a "Guided Simulator"?
              </h1>

              {/* Description */}
              <p className="text-gray-600 text-lg leading-relaxed mb-6">
                A structured walkthrough of case studies generated by real-life LLM outputs that demonstrate key learnings. Interact at set points—sometimes more, sometimes less—always with clear guidance.
              </p>

              {/* LLMs info */}
              <p className="text-gray-600 text-base leading-relaxed mb-8">
                LLMs used in the generation of text include: Mistral, Claude, Chat GPT & Llama 3.1 8B
              </p>

              {/* Start Simulator button */}
              <Button 
                onClick={handleStartSimulator}
                className="transition-all duration-200"
                style={{ 
                  display: 'flex',
                  flexDirection: 'row',
                  justifyContent: 'center',
                  alignItems: 'center',
                  padding: '15px 40px',
                  gap: '12px',
                  width: '220px',
                  height: '58px',
                  background: '#64DB96',
                  borderRadius: '100px',
                  border: 'none',
                  color: '#1F1F1F',
                  fontFamily: 'Manrope',
                  fontStyle: 'normal',
                  fontWeight: '700',
                  fontSize: '18px',
                  lineHeight: '28px'
                }}
              >
                Start Simulator
                <svg width="10" height="8" viewBox="0 0 12 10" fill="none" xmlns="http://www.w3.org/2000/svg">
                  <path d="M1 5H11M11 5L7 1M11 5L7 9" stroke="#1F1F1F" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
                </svg>
              </Button>
            </CardContent>
          </Card>
        </div>
      </main>
    </div>
  );
};

export default AboutSimulator;