import { useNavigate } from "react-router-dom";
import Header from "@/components/Header";
import Breadcrumb from "@/components/Breadcrumb";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";

const AboutSimulator = () => {
  const navigate = useNavigate();

  const handleStartSimulator = () => {
    navigate("/module/next-word-prediction");
  };

  return (
    <div className="min-h-screen bg-background">
      <Header />
      
      <main className="container mx-auto px-6 py-6">
        <Breadcrumb />
        <div className="max-w-4xl mx-auto flex items-center justify-center min-h-[600px] relative">
          <Card 
            className="w-full max-w-4xl transition-all duration-200 flex flex-col md:flex-row items-start p-8 md:p-10 gap-6 md:gap-8"
            style={{
              background: '#FFFFFF',
              border: '1px solid #C5C5C5',
              boxShadow: '0px 6px 15px rgba(62, 62, 62, 0.15)',
              borderRadius: '20px'
            }}
          >
            {/* Image inside the popup - aligned to top and smaller */}
            <img 
              src="/whatis.png" 
              alt="What is simulator cone" 
              className="w-full md:w-[325px] h-auto flex-shrink-0"
            />
            
            <CardContent className="p-0 w-full flex flex-col">
              {/* About label */}
              <div className="mb-6">
                <span className="text-gray-500 text-sm">About this Simulator</span>
              </div>

              {/* Main heading */}
              <h1 className="text-[40px] font-barlow-semi font-bold text-gray-900 leading-tight" style={{ marginBottom: '10px' }}>
                What is a "Guided Simulator"?
              </h1>

              {/* Description */}
              <p className="text-gray-600 text-lg leading-relaxed mb-6">
                A structured walkthrough of case studies generated by real-life LLM outputs that demonstrate key learnings. Interact at set points—sometimes more, sometimes less—always with clear guidance.
              </p>

              {/* LLMs info */}
              <p className="text-gray-600 text-base leading-relaxed mb-8">
                LLMs used in the generation of text include: Mistral, Claude, Chat GPT & Llama 3.1 8B
              </p>

              {/* Continue button */}
                <Button 
                  onClick={handleStartSimulator}
                  className="transition-all duration-200"
                  style={{ 
                    display: 'flex',
                    flexDirection: 'row',
                    justifyContent: 'center',
                    alignItems: 'center',
                    padding: '15px 40px',
                    gap: '12px',
                    width: '220px',
                    height: '58px',
                    background: '#64DB96',
                    borderRadius: '100px',
                    border: 'none',
                    color: '#1F1F1F',
                    fontFamily: 'Manrope',
                    fontStyle: 'normal',
                    fontWeight: '700',
                    fontSize: '18px',
                    lineHeight: '28px'
                  }}
                >
                  Start Simulator
                  <svg width="10" height="8" viewBox="0 0 12 10" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M1 5H11M11 5L7 1M11 5L7 9" stroke="#1F1F1F" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
                  </svg>
                </Button>
            </CardContent>
          </Card>
        </div>
      </main>
    </div>
  );
};

export default AboutSimulator;