import { useNavigate } from "react-router-dom";
import Header from "@/components/Header";
import Breadcrumb from "@/components/Breadcrumb";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";

const Introduction = () => {
  const navigate = useNavigate();

  const handleContinue = () => {
    navigate("/module/about-simulator");
  };

  return (
    <div className="min-h-screen bg-background">
      <Header />
      
      <main className="container mx-auto px-6 py-8">
        <Breadcrumb />
        <div className="max-w-4xl mx-auto flex items-center justify-center min-h-[600px] relative">
          <Card 
            className="transition-all duration-200"
            style={{
              boxSizing: 'border-box',
              display: 'flex',
              flexDirection: 'row',
              alignItems: 'flex-start',
              padding: '40px 50px 50px',
              gap: '30px',
              isolation: 'isolate',
              position: 'absolute',
              width: '845px',
              minHeight: 'auto',
              left: 'calc(50% - 845px/2 + 0.5px)',
              top: '100px',
              background: '#FFFFFF',
              border: '1px solid #C5C5C5',
              boxShadow: '0px 6px 15px rgba(62, 62, 62, 0.15)',
              borderRadius: '20px'
            }}
          >
            {/* Task image inside the popup - aligned to top and smaller */}
            <img 
              src="/task.png" 
              alt="Task notebook" 
              className="w-[325px] h-auto flex-shrink-0"
              style={{ marginTop: '10px' }}
            />
            
            <CardContent className="p-0 w-full flex flex-col">
              {/* Introduction label */}
              <div className="mb-6">
                <span className="text-gray-500 text-sm">Introduction</span>
              </div>

              {/* Main heading */}
              <h1 className="text-[40px] font-barlow-semi font-medium text-gray-900 leading-tight" style={{ marginBottom: '10px' }}>
                Your Task: Reporting on the EU AI Act
              </h1>

              {/* Description */}
              <p className="text-gray-600 text-lg leading-relaxed mb-8">
                In this simulator, you'll step into the role of a journalist preparing an article on the EU AI Act. Rather than starting from scratch, you'll work with preset prompts and see the real outputs generated by a large language model.
              </p>

              {/* Continue button */}
              <Button 
                onClick={handleContinue}
                className="transition-all duration-200"
                style={{ 
                  display: 'flex',
                  flexDirection: 'row',
                  justifyContent: 'center',
                  alignItems: 'center',
                  padding: '15px 40px',
                  gap: '12px',
                  width: '184px',
                  height: '58px',
                  background: '#64DB96',
                  borderRadius: '100px',
                  border: 'none',
                  color: '#1F1F1F',
                  fontFamily: 'Manrope',
                  fontStyle: 'normal',
                  fontWeight: '700',
                  fontSize: '18px',
                  lineHeight: '28px'
                }}
              >
                Continue
                <svg width="10" height="8" viewBox="0 0 12 10" fill="none" xmlns="http://www.w3.org/2000/svg">
                  <path d="M1 5H11M11 5L7 1M11 5L7 9" stroke="#1F1F1F" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
                </svg>
              </Button>
            </CardContent>
          </Card>
        </div>
      </main>
    </div>
  );
};

export default Introduction;